# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: git+https://github.com/oca/oca-addons-repo-template
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 16.0
org_name: ACSONE SA/NV
org_slug: acsone
rebel_module_groups: []
repo_description: 'Acsone experimental Odoo modules, most of them

    used in real projects.


    Caution: anything around here may change without notice!


    If you are interested in some features around here,

    get in touch and we''ll work together to put things

    in good shape and submit them to OCA repositories.'
repo_name: ACSONE Experimental Addons
repo_slug: acsone-addons
repo_website: https://github.com/acsone/acsone-addons
use_pyproject_toml: true
use_ruff: true

