# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.0
_src_path: git+https://github.com/oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 16.0
org_name: Odoo Community Association (OCA)ACSONE SA/NV
org_slug: acsone
rebel_module_groups: []
repo_description: 'Acsone experimental Odoo modules, most of them

    used in real projects.


    Caution: anything around here may change without notice!


    If you are interested in some features around here,

    get in touch and we''ll work together to put things

    in good shape and submit them to OCA repositories.'
repo_name: ACSONE Experimental Addons
repo_slug: acsone-addons
repo_website: https://github.com/acsone/acsone-addons
travis_apt_packages: []
travis_apt_sources: []

