name: pre-commit

on:
  pull_request:
    branches:
      - "14.0*"
  push:
    branches:
      - "14.0"
      - "14.0-ocabot-merge-*"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
